---
- name: Install nginx proxy

  hosts: "{{ target_hosts | default('nginx_proxy') }}"

  become: yes

  vars:

    acme_certificate_domain: "{{ nginx_proxy_url | urlsplit('hostname') }}"
    acme_certificate_chainfile: "/etc/nginx/{{ acme_certificate_domain }}.chain.crt"
    acme_certificate_keyfile: "/etc/nginx/{{ acme_certificate_domain }}.key"
    acme_certificate_add_ca: yes
    acme_certificate_aws_accesskey_id: "{{ nginx_proxy_aws_accesskey_id | default(lookup('env', 'AWS_ACCESS_KEY_ID')) }}"
    acme_certificate_aws_accesskey_secret: "{{ nginx_proxy_aws_accesskey_secret | default(lookup('env', 'AWS_SECRET_ACCESS_KEY')) }}"

    nginx_cleanup_config: yes
    nginx_install_from: os_repository
    nginx_cleanup_config_path:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-enabled/default.conf
      - /etc/nginx/sites-available/default
      - /etc/nginx/sites-available/default.conf
    nginx_extra_conf: |
      server_names_hash_bucket_size 64;
    nginx_main_template:
      conf_file_name: nginx.conf
      conf_file_location: /etc/nginx/
      user: "{{ 'www-data' if ansible_os_family == 'Debian' else 'nginx' }}"
      worker_processes: auto
      error_level: warn
      worker_connections: 1024
      http_enable: true
      http_settings:
        keepalive_timeout: 60
        cache: false
        rate_limit: false
        keyval: false
      stream_enable: false
      http_global_autoindex: false
      server_tokens: off
    nginx_http_template:
      default:
        listen:
          listen_default:
            ip: '*'
            port: 80
        server_name: "{{ acme_certificate_domain }}"
        conf_file_name: "{{ acme_certificate_domain }}.http.conf"
        https_redirect: yes
      proxy:
        listen:
          listen_proxy:
            ip: '*'
            port: 443
        server_name: "{{ acme_certificate_domain }}"
        conf_file_name: "{{ acme_certificate_domain }}.https.conf"
        ssl:
          key: "{{ acme_certificate_keyfile }}"
          cert: "{{ acme_certificate_chainfile }}"
          protocols: TLSv1.2 TLSv1.3
          ciphers: HIGH:!aNULL:!MD5
        reverse_proxy:
          locations:
            default:
              location: /
              proxy_pass: "http://{{ acme_certificate_domain }}"
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
                header_upgrade:
                  name: Upgrade
                  value: $http_upgrade
                header_connection:
                  name: Connection
                  value: Upgrade
                header_x_forwarded_for:
                  name: X-Forwarded-For
                  value: $proxy_add_x_forwarded_for
        upstreams:
          upstream:
            name: "{{ acme_certificate_domain }}"
            lb_method: least_conn
            zone_name: upstream
            zone_size: 32k
            sticky_cookie: false
            servers: "{{ nginx_proxy_upstream_servers }}"

  roles:

    - nephelaiio.plugins

  tasks:

    - fail:
        msg: "nginx_proxy_url must be defined"
      when: nginx_proxy_url is not defined

    - fail:
        msg: "only one of nginx_proxy_upstream_group and nginx_proxy_upstream_servers must be defined"
      when: checklist | select() | list | length != 1
      vars:
        checklist:
          - "{{ nginx_proxy_upstream_group is defined }}"
          - "{{ nginx_proxy_upstream_servers is defined }}"

    - block:

        - name: gather facts from upstream servers
          setup:
          delegate_to: "{{ item }}"
          delegate_facts: yes
          loop: "{{ groups[nginx_proxy_upstream_group] | list }}"

        - name: build list of upstream servers
          set_fact:
            nginx_proxy_upstream_servers: "{{ (nginx_proxy_upstream_servers | default({})) | combine ({ item: nginx_proxy_item_server}) }}"
          loop: "{{ groups[nginx_proxy_upstream_group] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"
          vars:
            nginx_proxy_item_server:
              address: "{{ item }}"
              port: "{{ nginx_proxy_upstream_port | default('80') }}"
              weight: 1
              health_check: max_fails=3 fail_timeout=5s

      when: nginx_proxy_upstream_servers is not defined

    - name: install nginx
      import_role:
        name: nginxinc.nginx
      vars:
        nginx_http_template_enable: no
        nginx_main_template_enable: no

    - name: define extra nginx parameters
      copy:
        content: "{{ nginx_extra_conf }}"
        dest: "{{ nginx_main_template.conf_file_location }}/conf.d/extra.conf"
        owner: "{{ nginx_main_template.user }}"
      notify: restart nginx

    - name: generate certificates
      import_role:
        name: nephelaiio.acme_certificate_route53

    - name: configure nginx
      import_role:
        name: nginxinc.nginx
      vars:
        nginx_http_template_enable: yes
        nginx_main_template_enable: yes

    - name: update pdns record
      uri:
        url: "{{ nginx_proxy_pdns_url }}/api/v1/servers/localhost/zones/{{ pdns_url_zone }}"
        method: PATCH
        return_content: yes
        body_format: json
        body:
          rrsets:
            - name: "{{ pdns_url_host }}"
              type: A
              ttl: 3600
              changetype: REPLACE
              records:
                - content: "{{ ansible_default_ipv4.address }}"
                  disabled: no
                  set-ptr: no
                  comments: []
        headers:
          X-API-Key: "{{ nginx_proxy_pdns_api_key }}"
        status_code: 204
      vars:
        pdns_url_host: "{{ acme_certificate_domain }}."
        pdns_url_zone: "{{ pdns_url_host | split_with('.') | tail | join('.') }}"
      when:
        - nginx_proxy_pdns_url is defined
        - nginx_proxy_pdns_api_key is defined

  handlers:

    - name: restart nginx
      service:
        name: nginx
        state: restarted
